# Generated by Django 3.2.4 on 2021-06-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novartisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbook',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactbook',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
